pages/about/differences.html
pages/phases/certificate.md
pages/phases/phone-assessment-interviews/reviewing-sme-assessments.md
pages/phases/reviewing-resumes/index.html

Every other phase has been "cleaned up". This little one is the last one. I'm going to do another pass for toolkit items and guidance before I open this up for review.

[WIP] Tighten up certificate docs

---

pages/about/differences.html
pages/phases/certificate.md

This incorporates Stephanie's feedback in #4. Have at it.

More cert feedback from Stephanie

---

pages/about/differences.html

Closes https://github.com/usds/OPM_pilot/issues/714 (I know that won't close the issue but just linking it up regardless).

Update "Understanding the Process" based on new approved language

---

_data/competencies.yml
pages/research/phase-2/engineering.html
pages/research/phase-2/product.html

Added a product prototype page that will be located:
https://federalist-proxy.app.cloud.gov/site/labopm/competitive-hiring-pilot/research/phase-2/test-1/product/
Also:
- removed the "52 weeks requirement" option from the dropdown
- alphabetized the engineering competencies

Added Product Prototype Page

---

pages/phases/getting-started/index.html
pages/phases/job-analysis/index.html

@stephaniefaith found a couple of small calculation issues.

Small content updates

---

pages/phases/job-analysis/converting-job-tasks-to-competencies.md
pages/phases/job-analysis/documenting-job-tasks.md
pages/phases/job-analysis/index.html
pages/phases/job-announcement/create-announcement-on-usajobs.md

Adds small clarifications as follows:
- Job Analysis:
- Specifies that job tasks and competencies can encompass EQ.
- Specifies that hiring managers should participate in the workshop.
- Job Announcement: Adds clarification that while the occupational questionnaire is still used for biographical information on the applicant, the assessment portion is supplanted by the phone assessment interviews as the examination.

Small site updates

---

pages/changelog.md

Adding a change log entry for the two toolkit update PRs and the little bitty tidbits in #41.

Changelog updates for #38, #39, and #41

---

_includes/toolkit/phone-assessment-interviews.html

Fixing a bug (removing an extra "{" ) in this file that way it's able to be hosted on github pages.

Making it so that the page can be hosted on github pages. 

---

Gemfile
Gemfile.lock
_config.yml
atom.xml
robots.txt
sitemap.xml

@sharmaneil - This is the start of adding search via search.gov. It creates a atom.xml and sitemap.xml and alters the robot.txt file such that search.gov, once I register the site, will start indexing our pages and creating search results for them. I'd like to push these changes out so I can confirm the indexing before I add the search box to our header.

Starts search

---

_config.yml
_includes/_head.html
atom.xml
package-lock.json
package.json
pages/changelog.md
robots.txt

* Updates robots to hopefully block google while allowing access to search.gov. 
* Updates the changelog to fix the broken links [Fixes #67] and mention the change of case studies to results. 
* Fixes the atom.xml feed to make it valid for consumption by search.gov.
* Updates a few npm packages.

A few website updates

---

pages/phases/job-announcement/recruiting.md

addresses https://github.com/usds/SME-QA-Website/issues/95

add note to clarify how to use searched resumes

---

_data/navigation.yml
pages/phases/getting-started/identifying-appropriate-positions.md
pages/phases/job-analysis/defining-proficiency-levels.md
pages/phases/job-analysis/index.html
pages/phases/job-announcement/create-job-announcement.md

A few changes that Stephanie, Will, Neil, and I did in person this morning.

More updates

---

pages/phases/getting-started/time-commitment.md

Update grammar, wording, and a few numbers based on https://github.com/usds/SME-QA-Website/issues/133#issuecomment-572157393
Addresses some of the content in https://github.com/usds/SME-QA-Website/issues/133

quick update of the website page on time commitment

---

pages/phases/job-analysis/converting-job-tasks-to-competencies.md
pages/phases/job-analysis/documenting-job-tasks.md

I changed the name of the folder of the images but didn't update the link

Fix image link

---

_includes/_banner-beta.html
pages/phases/job-announcement/configuring-usas.md

Add the SMEQA e-mail to the website

Update website e-mail address

---

pages/phases/job-analysis/index.html

This PR addresses https://github.com/usds/SME-QA-Website/issues/277

Add instructions to prep resumes for job analysis

---

pages/phases/job-analysis/creating-assessments-from-competencies.md

Adding items that were pulled from https://github.com/usds/SME-QA-Website/pull/292

adding written assessment tips to JOA section

---

_data/navigation.yml
pages/phases/certificate/notifications.md

We can't find them when they are under assessments

moving NOR templates to cert section

---

pages/phases/getting-started/index.html

Added update from our team recommendations.

Update Getting Started HR Outcomes

---

pages/about/authority.html

I wrote this with a direct quote of the law instead of a paraphrase, we can adjust if we need.

update with shared law citation

---

pages/phases/job-announcement/index.html

We need to make a final list of things to check before any JOA goes live

add hard JOA checklist

---

pages/home.html

wh link led to 404, switched to federal register

update link to exec order

---

pages/phases/job-announcement/create-job-announcement.md
pages/phases/job-announcement/index.html

The length of the checklist makes me want to move some of the content to https://smeqa.usds.gov/hiring-phases/job-announcement/creating-job-announcement/ - thoughts?

edits to JOA checklist

---

pages/phases/job-analysis/defining-proficiency-levels.md

Adopting NIH and OMB guidance into the proficiency page and cleaning up the text. Thank you @sstrassberg for transcribing!

Signifiant edits to proficiency page

---

_includes/results/pilot-hiring-actions-summary.html

Adds automatic calculation for results display. The current state is shown in the following screenshot.

Add calculation for agencies and actions

---

_includes/toolkit/job-analysis.html
toolkit/job-analysis/agenda-for-job-analysis-workshop.md
toolkit/job-analysis/job-analysis-prep-email.md

adding prep e-mail and editing agenda

Job analysis materials
